"""Generates Pydantic v2 models into `browser_service.contracts.generated`
from the JSON Schema build artifacts committed at
`packages/contracts/schema/*.schema.json`.

Per ADR 0004
(`docs/architecture/decisions/0004-canonical-schema-ownership.md`),
`packages/contracts/src/` (TypeScript/Zod) is the single source of truth.
This script never hand-authors a Pydantic model; it drives
`datamodel-code-generator` off the committed JSON Schema so the Python
models cannot drift from what TypeScript emits without the drift check
below catching it.

Usage (run from `services/browser`, via `uv run`):

    uv run python scripts/generate_contracts.py            regenerate in place
    uv run python scripts/generate_contracts.py --check     fail (exit 1) if the
                                                              committed generated
                                                              files are stale
                                                              relative to
                                                              packages/contracts/schema/

Prerequisite: `packages/contracts/schema/*.schema.json` must already be
up to date with `packages/contracts/src/` -- run
`npm run generate:schema` (or `npm run check:schema`) in
`packages/contracts` first. This script does not regenerate the JSON
Schema itself, only the Pydantic models derived from it.

Bespoke Python-side behavior that the generated models cannot express
(the http/https URL-scheme check, the recursive credential-field
rejection, and the cancellation cross-field `taskId`-required rule) lives
in the thin wrapper module `browser_service/contracts/_validators.py` and
`browser_service/contracts/__init__.py` -- NOT in these generated files,
per ADR 0004's "Negative consequences" note. Do not hand-edit anything
under `browser_service/contracts/generated/`; it is fully regenerated by
this script and any manual edit is silently discarded (and will be
flagged as drift the next time `--check` runs).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
SCHEMA_DIR = REPO_ROOT / "packages" / "contracts" / "schema"
SERVICE_ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = SERVICE_ROOT / "src" / "browser_service" / "contracts" / "generated"

GENERATED_FILE_HEADER = '''"""GENERATED FILE -- DO NOT EDIT BY HAND.

Source of truth: packages/contracts/src/ (TypeScript/Zod), via the
committed JSON Schema artifact packages/contracts/schema/{stem}.schema.json.
Regenerate with (from services/browser): uv run python scripts/generate_contracts.py
See docs/features/p00-f03-tool-contract.md and ADR 0004 for the generation
policy and the drift check (`--check`) wired into root `npm run lint`.
"""

'''

GENERATED_INIT_CONTENT = '''"""GENERATED PACKAGE -- DO NOT EDIT BY HAND.

Each sibling module in this package is generated 1:1 from a committed
JSON Schema file in packages/contracts/schema/. See
scripts/generate_contracts.py and docs/features/p00-f03-tool-contract.md.
"""
'''


def _strip_datetime_pattern(node: Any) -> Any:
    """Drop a sibling ``pattern`` wherever ``format: date-time`` is present.

    zod v4's ``z.toJSONSchema()`` emits both ``format: date-time`` *and* a
    regex ``pattern`` for `IsoDateTimeSchema` (see
    `packages/contracts/src/primitives.ts`). Both are valid JSON Schema, but
    datamodel-code-generator maps ``format: date-time`` to Pydantic's
    ``AwareDatetime`` and then tries to also attach the ``pattern`` as a
    `Field(pattern=...)` constraint -- which Pydantic rejects at class-
    definition time for a datetime-typed field (`TypeError`, not a
    `ValidationError`, so it fails every parse, not just invalid input).
    `AwareDatetime` already enforces RFC 3339 with an explicit offset, so the
    regex is redundant for the generated Python side; only the JSON Schema
    artifact keeps it (useful for non-Pydantic consumers).
    """
    if isinstance(node, dict):
        if node.get("format") == "date-time" and "pattern" in node:
            node = {k: v for k, v in node.items() if k != "pattern"}
        return {k: _strip_datetime_pattern(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_strip_datetime_pattern(v) for v in node]
    return node


def to_snake_case(stem: str) -> str:
    return stem.replace("-", "_")


def to_pascal_case(stem: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[-_]", stem) if part)


def discover_schema_files() -> list[Path]:
    if not SCHEMA_DIR.exists():
        raise SystemExit(
            f"schema directory not found: {SCHEMA_DIR}\n"
            "Run `npm run generate:schema` in packages/contracts first."
        )
    files = sorted(SCHEMA_DIR.glob("*.schema.json"))
    if not files:
        raise SystemExit(f"no *.schema.json files found under {SCHEMA_DIR}")
    return files


def generate_one(schema_path: Path, out_dir: Path) -> Path:
    stem = schema_path.name[: -len(".schema.json")]
    module_name = to_snake_case(stem)
    class_name = to_pascal_case(stem)
    out_path = out_dir / f"{module_name}.py"
    out_dir.mkdir(parents=True, exist_ok=True)

    raw_schema = json.loads(schema_path.read_text(encoding="utf-8"))
    preprocessed_schema = _strip_datetime_pattern(raw_schema)
    # Keep the original filename inside its own temp dir: datamodel-code-
    # generator echoes the input filename into a `# generated by ...`
    # comment, and that comment must name the real schema file, not a
    # scratch path.
    preprocessed_dir = Path(tempfile.mkdtemp(prefix="browser-service-contracts-input-"))
    preprocessed_input = preprocessed_dir / schema_path.name
    preprocessed_input.write_text(json.dumps(preprocessed_schema, indent=2), encoding="utf-8")

    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(preprocessed_input),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(out_path),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.12",
        "--class-name",
        class_name,
        "--collapse-root-models",
        "--enum-field-as-literal",
        "all",
        "--use-standard-collections",
        "--use-union-operator",
        "--field-constraints",
        "--disable-timestamp",
        # The contract is meant to be *closed*: Pydantic v2's default lax
        # mode coerces e.g. bool from "yes"/1/"true" and int from numeric
        # strings, which would silently accept fixtures the contract is
        # supposed to reject (see docs/features/p00-f03-tool-contract.md).
        # Strict types make the generated models reject anything but the
        # exact JSON type the schema declares.
        "--strict-types",
        "str",
        "bytes",
        "int",
        "float",
        "bool",
        # Deliberately black+isort, not `builtin`: the builtin formatter's
        # line-wrapping turned out to depend on the calling terminal's
        # width (COLUMNS / tty size), which made output non-deterministic
        # across otherwise-identical invocations (e.g. this script's own
        # `subprocess.run` vs. a direct CLI call) and produced false
        # positives in `--check`. black's wrapping is driven by a fixed
        # line-length, not the environment, so it is reproducible.
        "--formatters",
        "black",
        "--formatters",
        "isort",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT, check=False)
    if result.returncode != 0:
        raise SystemExit(
            f"datamodel-code-generator failed for {schema_path.name}:\n"
            f"{result.stdout}\n{result.stderr}"
        )

    body = out_path.read_text(encoding="utf-8")
    header = GENERATED_FILE_HEADER.format(stem=stem)
    out_path.write_text(header + body, encoding="utf-8", newline="\n")
    return out_path


def generate_all(out_dir: Path) -> list[Path]:
    files = [generate_one(schema_path, out_dir) for schema_path in discover_schema_files()]
    init_path = out_dir / "__init__.py"
    init_path.write_text(GENERATED_INIT_CONTENT, encoding="utf-8", newline="\n")
    files.append(init_path)
    return files


def run_generate() -> None:
    files = generate_all(GENERATED_DIR)
    print(f"Generated {len(files)} file(s) into {GENERATED_DIR}:")
    for f in sorted(files):
        print(f"  {f.relative_to(SERVICE_ROOT)}")


def run_check() -> None:
    drift = False
    with tempfile.TemporaryDirectory(prefix="browser-service-contracts-check-") as tmp:
        tmp_dir = Path(tmp) / "generated"
        fresh_files = generate_all(tmp_dir)
        fresh_names = {f.name for f in fresh_files}
        committed_names: set[str] = set()
        if GENERATED_DIR.exists():
            committed_names = {f.name for f in GENERATED_DIR.glob("*.py")}

        for name in sorted(fresh_names):
            committed_path = GENERATED_DIR / name
            fresh_path = tmp_dir / name
            if not committed_path.exists():
                print(f"DRIFT: {name} would be generated but is missing", file=sys.stderr)
                drift = True
                continue
            committed_text = committed_path.read_text(encoding="utf-8")
            fresh_text = fresh_path.read_text(encoding="utf-8")
            if committed_text != fresh_text:
                print(f"DRIFT: {name} does not match packages/contracts/schema/", file=sys.stderr)
                drift = True

        for name in sorted(committed_names - fresh_names):
            print(f"DRIFT: {name} is committed but no longer generated (stale)", file=sys.stderr)
            drift = True

    if drift:
        print(
            "\nPydantic contracts check FAILED. From services/browser, run "
            "`uv run python scripts/generate_contracts.py` and commit the result.",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"Pydantic contracts check passed: {GENERATED_DIR} matches packages/contracts/schema/.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()
    if args.check:
        run_check()
    else:
        run_generate()


if __name__ == "__main__":
    main()
