import { z } from "zod";
import { IdSchema } from "./primitives";

/**
 * Correlation metadata carried on every tool-call message (invocation,
 * success/error result, progress event, cancellation request/result).
 *
 * Field names and generation points mirror the ID-propagation table in
 * `docs/architecture/system.md`:
 *  - `requestId` -- generated by the orchestrator at HTTP ingress (and
 *    again for each distinct outbound call it initiates); always present.
 *  - `userId` -- established at auth/session; always present; stamped as
 *    the owner on durable records; NEVER forwarded into model message
 *    content.
 *  - `sessionId` -- generated by the browser service at session creation;
 *    absent until a session exists (e.g. the very first `browse` call in a
 *    fresh conversation may not have one yet).
 *  - `taskId` -- generated by the browser service (the RQ job id) when a
 *    command is enqueued; absent until a task has been dispatched.
 */
export const CorrelationMetadataSchema = z
  .object({
    requestId: IdSchema,
    userId: IdSchema,
    sessionId: IdSchema.optional(),
    taskId: IdSchema.optional(),
  })
  .strict();

export type CorrelationMetadata = z.infer<typeof CorrelationMetadataSchema>;
